-- ============================================================
-- RetailFlow Database Seed Script
-- Run after EF migrations to populate reference data
-- ============================================================

USE RetailFlowDb;
GO

-- ── Roles ────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM Roles WHERE Id = 1)
BEGIN
    SET IDENTITY_INSERT Roles ON;
    INSERT INTO Roles (Id, Name) VALUES
        (1, 'Customer'),
        (2, 'Admin'),
        (3, 'WarehouseManager'),
        (4, 'FinanceManager');
    SET IDENTITY_INSERT Roles OFF;
    PRINT 'Roles seeded.';
END
GO

-- ── Admin user (password: Admin@1234) ────────────────────────
-- Hash generated by PasswordHelper.HashPassword("Admin@1234")
IF NOT EXISTS (SELECT 1 FROM Users WHERE Email = 'admin@retailflow.com')
BEGIN
    INSERT INTO Users (FirstName, LastName, Email, PasswordHash, RoleId, IsActive, CreatedAt)
    VALUES (
        'System',
        'Admin',
        'admin@retailflow.com',
        '100000.PLACEHOLDER_HASH_REPLACE_WITH_ACTUAL',
        2,
        1,
        GETUTCDATE()
    );
    PRINT 'Admin user seeded. IMPORTANT: Update PasswordHash with actual hash.';
END
GO

-- ── Sample inventory entries ─────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM Inventory WHERE ProductId = 'sample-product-1')
BEGIN
    INSERT INTO Inventory (ProductId, QuantityAvailable, WarehouseLocation, UpdatedAt, LowStockThreshold)
    VALUES
        ('sample-product-1', 100, 'Warehouse-A, Shelf-1', GETUTCDATE(), 10),
        ('sample-product-2', 50,  'Warehouse-A, Shelf-2', GETUTCDATE(), 5),
        ('sample-product-3', 200, 'Warehouse-B, Shelf-1', GETUTCDATE(), 20);
    PRINT 'Sample inventory seeded.';
END
GO

PRINT 'Seed script completed successfully.';
GO
